<a href="https://colab.research.google.com/github/Chandu1722/ML/blob/main/Kaggle/CustomerChurn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import pandas as pd

In [56]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')
train.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

In [57]:
test.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,594194,Female,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,115.55,8061.50
1,594195,Female,0,Yes,No,71,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),19.80,1336.50
2,594196,Male,0,No,No,12,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),55.55,633.55
3,594197,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),84.10,6457.15
4,594198,Female,0,No,No,15,Yes,No,Fiber optic,Yes,No,No,No,Yes,Yes,Month-to-month,No,Electronic check,90.35,1233.65

In [58]:
test.isna().sum()

id                  0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
dtype: int64

In [61]:
train=train.dropna()

In [39]:
train

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594189,594189,Male,0,No,No,57,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Two year,No,Bank transfer (automatic),97.55,5460.70,No
594190,594190,Female,0,No,No,72,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,Two year,No,Bank transfer (automatic),91.95,6782.15,No
594191,594191,Female,0,Yes,No,72,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),24.40,1871.90,No
594192,594192,Female,0,No,No,32,Yes,Yes,Fiber optic,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,86.00,2847.20,No
594193,594193,Female,1,Yes,No,2,Yes,No,DSL,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,54.55,108.05,Yes

In [60]:
train['gender']=train['gender'].str.strip().map({'Female':0,'Male':1})
test['gender']=test['gender'].str.strip().map({'Female':0,'Male':1})

In [62]:
for col in train.columns:
  if train[col].dtype=='object':
    if len(train[col].unique())==2:
      train[col]=train[col].str.strip().map({'No':0,'Yes':1})
for col in test.columns:
  if test[col].dtype=='object':
    if len(test[col].unique())==2:
      test[col]=test[col].str.strip().map({'No':0,'Yes':1})

In [26]:
train

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,1,0,1,1,29,1,No,DSL,Yes,...,Yes,Yes,No,No,One year,1,Mailed check,60.10,1653.85,0
1,1,1,0,1,1,58,1,No,DSL,Yes,...,No,Yes,Yes,No,Two year,0,Credit card (automatic),69.50,3778.20,0
2,2,1,0,1,0,58,1,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,1,Electronic check,100.40,5841.35,0
3,3,0,0,0,0,1,1,No,Fiber optic,No,...,No,No,No,No,Month-to-month,1,Electronic check,69.70,70.70,1
4,4,0,0,0,0,1,1,No,Fiber optic,No,...,No,No,No,No,Month-to-month,1,Electronic check,70.45,70.45,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594189,594189,1,0,0,0,57,1,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Two year,0,Bank transfer (automatic),97.55,5460.70,0
594190,594190,0,0,0,0,72,1,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,Two year,0,Bank transfer (automatic),91.95,6782.15,0
594191,594191,0,0,1,0,72,1,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,0,Credit card (automatic),24.40,1871.90,0
594192,594192,0,0,0,0,32,1,Yes,Fiber optic,No,...,No,No,No,Yes,Month-to-month,1,Electronic check,86.00,2847.20,0
594193,594193,0,1,1,0,2,1,No,DSL,No,...,No,No,Yes,No,Month-to-month,1,Electronic check,54.55,108.05,1

In [64]:
train['MultipleLines']=train['MultipleLines'].str.strip().map({'No':0,'No phone service':1,'Yes':2})
test['MultipleLines']=test['MultipleLines'].str.strip().map({'No':0,'No phone service':1,'Yes':2})

AttributeError: Can only use .str accessor with string values!

In [43]:
train['InternetService'].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [65]:
train['InternetService']=train['InternetService'].str.strip().map({'Fiber optic':0,'DSL':1,'No':2})
test['InternetService']=test['InternetService'].str.strip().map({'Fiber optic':0,'DSL':1,'No':2})

In [66]:
for col in train.columns:
  if train[col].dtype=='object':
    print(col,train[col].unique())
for col in test.columns:
  if test[col].dtype=='object':
    print(col,test[col].unique())

OnlineSecurity ['Yes' 'No' 'No internet service']
OnlineBackup ['No' 'Yes' 'No internet service']
DeviceProtection ['Yes' 'No' 'No internet service']
TechSupport ['Yes' 'No' 'No internet service']
StreamingTV ['No' 'Yes' 'No internet service']
StreamingMovies ['No' 'Yes' 'No internet service']
Contract ['One year' 'Two year' 'Month-to-month']
PaymentMethod ['Mailed check' 'Credit card (automatic)' 'Electronic check'
 'Bank transfer (automatic)']
OnlineSecurity ['Yes' 'No internet service' 'No']
OnlineBackup ['Yes' 'No internet service' 'No']
DeviceProtection ['Yes' 'No internet service' 'No']
TechSupport ['Yes' 'No internet service' 'No']
StreamingTV ['Yes' 'No internet service' 'No']
StreamingMovies ['Yes' 'No internet service' 'No']
Contract ['Two year' 'Month-to-month' 'One year']
PaymentMethod ['Electronic check' 'Bank transfer (automatic)' 'Credit card (automatic)'
 'Mailed check']

In [67]:
train['OnlineSecurity']=train['OnlineSecurity'].str.strip().map({'No':0,'No internet service':1,'Yes':2})
train['OnlineBackup']=train['OnlineBackup'].str.strip().map({'No':0,'No internet service':1,'Yes':2})
train['DeviceProtection']=train['DeviceProtection'].str.strip().map({'No':0,'No internet service':1,'Yes':2})
train['TechSupport']=train['TechSupport'].str.strip().map({'No':0,'No internet service':1,'Yes':2})
train['StreamingTV']=train['StreamingTV'].str.strip().map({'No':0,'No internet service':1,'Yes':2})
train['StreamingMovies']=train['StreamingMovies'].str.strip().map({'No':0,'No internet service':1,'Yes':2})
train['Contract']=train['Contract'].str.strip().map({'Month-to-month':0,'One year':1,'Two year':2})
train['PaymentMethod']=train['PaymentMethod'].str.strip().map({'Electronic check':0,'Mailed check':1,'Bank transfer (automatic)':2,'Credit card (automatic)':3})
test['OnlineSecurity']=test['OnlineSecurity'].str.strip().map({'No':0,'No internet service':1,'Yes':2})
test['OnlineBackup']=test['OnlineBackup'].str.strip().map({'No':0,'No internet service':1,'Yes':2})
test['DeviceProtection']=test['DeviceProtection'].str.strip().map({'No':0,'No internet service':1,'Yes':2})
test['TechSupport']=test['TechSupport'].str.strip().map({'No':0,'No internet service':1,'Yes':2})
test['StreamingTV']=test['StreamingTV'].str.strip().map({'No':0,'No internet service':1,'Yes':2})
test['StreamingMovies']=test['StreamingMovies'].str.strip().map({'No':0,'No internet service':1,'Yes':2})
test['Contract']=test['Contract'].str.strip().map({'Month-to-month':0,'One year':1,'Two year':2})
test['PaymentMethod']=test['PaymentMethod'].str.strip().map({'Electronic check':0,'Mailed check':1,'Bank transfer (automatic)':2,'Credit card (automatic)':3})

In [47]:
train

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,1,0,1,1,29,1,0,1,2,...,2,2,0,0,1,1,1,60.10,1653.85,0
1,1,1,0,1,1,58,1,0,1,2,...,0,2,2,0,2,0,3,69.50,3778.20,0
2,2,1,0,1,0,58,1,2,0,0,...,0,0,2,2,0,1,0,100.40,5841.35,0
3,3,0,0,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,69.70,70.70,1
4,4,0,0,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,70.45,70.45,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594189,594189,1,0,0,0,57,1,2,0,0,...,2,0,2,2,2,0,2,97.55,5460.70,0
594190,594190,0,0,0,0,72,1,2,1,2,...,2,2,2,2,2,0,2,91.95,6782.15,0
594191,594191,0,0,1,0,72,1,2,2,1,...,1,1,1,1,2,0,3,24.40,1871.90,0
594192,594192,0,0,0,0,32,1,2,0,0,...,0,0,0,2,0,1,0,86.00,2847.20,0
594193,594193,0,1,1,0,2,1,0,1,0,...,0,0,2,0,0,1,0,54.55,108.05,1

In [48]:
corr=train.corr()['Churn'].abs().sort_values(ascending=False)
print(corr)

Churn               1.000000
Contract            0.449285
tenure              0.418453
InternetService     0.408363
PaymentMethod       0.399258
OnlineSecurity      0.356786
TechSupport         0.342550
PaperlessBilling    0.285107
MonthlyCharges      0.272997
OnlineBackup        0.246620
Dependents          0.240369
SeniorCitizen       0.236362
Partner             0.228212
DeviceProtection    0.218451
TotalCharges        0.218365
MultipleLines       0.109689
PhoneService        0.034843
id                  0.012971
StreamingMovies     0.008041
gender              0.006808
StreamingTV         0.005108
Name: Churn, dtype: float64

In [69]:
from sklearn.model_selection import train_test_split
X=train.drop(columns=['id','Churn'])
y=train['Churn']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
y_full=test.drop(columns=['id'])

In [70]:
from sklearn.metrics import roc_auc_score

In [52]:
from sklearn.ensemble import RandomForestClassifier
modelRF=RandomForestClassifier()
modelRF.fit(X_train,y_train)
y_pred_RF=modelRF.predict_proba(X_test)[:,1]
aucRF=roc_auc_score(y_test,y_pred_RF)
print(aucRF)

0.8956392865319228

In [72]:

Y_pred_full=modelRF.predict_proba(y_full)[:,1]
sub=pd.DataFrame({'id':test['id'],'Churn':Y_pred_full})
sub.to_csv('SubmissionRF.csv',index=False)

In [73]:
from xgboost import XGBClassifier
modelXGB=XGBClassifier()
modelXGB.fit(X_train,y_train)
y_pred_XGB=modelXGB.predict_proba(y_full)[:,1]
subm=pd.DataFrame({'id':test['id'],'Churn':y_pred_XGB})
subm.to_csv('SubmissionXGB.csv',index=False)